---
name: App-CCSV
version: 0.01
author:
  - 'Karlheinz Zoechling <kh@ibeatgarry.com>'
abstract: Command line "auto split" for easy working on CSV files via perl -ne
license: perl
requires:
  Config::General: 0
  Text::CSV_XS: 0
build_requires:
  Test::More: 0
provides:
  App::CCSV:
    file: lib/App/CCSV.pm
    version: 0.01
  TieCSV:
    file: lib/App/CCSV/TieCSV.pm
    version: 0.01
generated_by: Module::Build version 0.26
